### ISSUE TITLE
Change unit suffixes to SI

### ISSUE THREAD

**Issue by olorin** [machiavellian/machiavelli#94]
'M' for 'millions' and 'B' for 'billions' is nonstandard and really confusing. Could we change these to 'm' and 'g' for 'mega' and 'giga'?

**Comment by glasnt** [comment]
Is this request for within the scope of the y-axis on graphs, and or hover details?

**Comment by fractalcat** [comment]
Yes (both), and wherever else these are displayed (because inconsistency would be even more confusing than nonstandard suffixes).

**Comment by fractalcat** [comment]
Don't worry about implementing this by the way, if you have no objections I'll do it myself at some point; it's around time I got more familiar with the codebase.

**Comment by glasnt** [comment]
If you want to be diving into this, you'll be playing with some Rickshaw Fixtures and possibly incorporating _unit values for the vaultaire store. 

For the JS stuff, I might need to move my own Rickshaw fork into the anchor account, but that is totally doable.

**Comment by glasnt** [comment]
[![No Maintenance Intended](http://unmaintained.tech/badge.svg)](http://unmaintained.tech/)
