### ISSUE TITLE
Remove hard requirement for redis

### ISSUE THREAD

**Issue by glasnt** [machiavellian/machiavelli#96]
It's super useful in cases where retrieving a list of metrics is hard or painful, however, it's not really a hard requirement of the system. 

Either remove it's requirement, and make any existing implemented store libraries suck it up, or, work out a way to flag store libraries that require it, and only do the forceful redis check if it's going to be used by any of these store libraries (currently implemented in `config/initializes/redis_test`)

**Comment by glasnt** [comment]
Also, should extend to allow for passwords in redis instance

**Comment by developersteve** [comment]
+1

**Comment by glasnt** [comment]
[![No Maintenance Intended](http://unmaintained.tech/badge.svg)](http://unmaintained.tech/)
